[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "dfqueue"
version = "0.1.0"
keywords = ["queue", "fault tolerant", "decoupled"]
categories = ["no-std", "abstractions"]
license = "MIT"

[dependencies]
spin = "0.4.5"
atomic = "0.3.4"

