[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "dfqueue"
version = "0.1.0"
keywords = ["queue", "fault tolerant", "decoupled", "interrupt", "irq-safe"]
categories = ["no-std", "abstractions"]
license = "MIT"

[dependencies]
atomic = "0.3.4"
spin = "0.4.5"

